"""Command line for the report-specific half.

Everything generic moved to `parnassix`, which this app now depends on:
`parnassix sync`, `parnassix query`, `parnassix machine`, `parnassix models` and
`parnassix compare` all work here unchanged and against the same
`pythoness.toml`. What is left is the contract.

Keeping a second copy of `ingest` and `query` wrapped around the library would
have made this app look like it still owned them, which is exactly the thing
the extraction was for.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console

from .report import SCHEMA_VERSION, ContractError, time_span_issues, validate_source_ref
from .wire import ReportSchemaWire

app = typer.Typer(
    add_completion=False,
    help="Parnassix: pythoness, wearing the report-schema contract.",
)
console = Console()


@app.command()
def contract() -> None:
    """Which contract version this build carries, and where it came from."""
    console.print(f"[bold]@repo/report-schema[/bold] {SCHEMA_VERSION}")
    console.print(f"wire: {ReportSchemaWire().version}")
    console.print(
        "\n[dim]Generated by scripts/generate_models.py from "
        "packages/report-schema/schema/report-schema.json.[/dim]"
    )
    console.print(
        "[dim]Corpus commands live in `parnassix` — "
        "parnassix sync, parnassix query, parnassix cite, parnassix mcp.[/dim]"
    )


@app.command()
def check(
    path: Annotated[Path, typer.Argument(help="A JSON file holding refs or spans")],
    kind: Annotated[
        str, typer.Option(help="source-ref | time-span")
    ] = "source-ref",
) -> None:
    """Validate JSON against the rules JSON Schema cannot carry.

    The same check the ingestion path applies, reachable without running one --
    which is what makes it usable on an agent's output during development.
    """
    payload = json.loads(path.read_text())
    items = payload if isinstance(payload, list) else [payload]

    failures = 0
    for index, item in enumerate(items):
        try:
            if kind == "source-ref":
                validate_source_ref(item)
            else:
                issues = time_span_issues(item)
                if issues:
                    raise ContractError(
                        "; ".join(f"{'.'.join(i.path)}: {i.message}" for i in issues)
                    )
        except (ContractError, ValueError) as exc:
            failures += 1
            console.print(f"[red]{index}[/red]: {exc}")

    if failures:
        console.print(f"\n[red]{failures} of {len(items)} failed.[/red]")
        raise typer.Exit(code=1)
    console.print(f"[green]{len(items)} ok.[/green]")


@app.command()
def serve(
    host: Annotated[str, typer.Option()] = "127.0.0.1",
    port: Annotated[int, typer.Option()] = 8000,
    reload: Annotated[bool, typer.Option()] = False,
) -> None:
    """Serve the pipeline: pythoness's tools plus the contract endpoints."""
    from .api.app import serve as run

    run(host=host, port=port, reload=reload)


if __name__ == "__main__":
    app()
